# Counting DNA Nucleotides
data = "GGCGTCCCTCTACCGGTTACAACGCTATATCGCTATGCGTCATTAATCAAGTGGTCCCCTGGGGTAGACCGAGACGATCGGAGGGAACTAGGATGAGCAGAACGGTGCTACCGGCTTTGCTTAACACGTGTGTCTTTTACGATGTACGGTGCTATCTTTGTATACTCCGTCCGCCTGGTCTAAGTTCAATGCTGAGGCAAGGTCAAACCCCTTTAAATCCTTATCGCATTAGCGTGTCGTAAAATTCGTCACTTCTATTTTTCTCAGGTGGAAAGGTCTCATTGATGCTCCTGCCAGCAGCGGTCAAGAGAACGTCGTGTCAAATACTTGACAATACGGAGGCAACTCTAAGAAAAGTGAGGGCATTTCTGAGATGCTTATCCGGTTCCGGGGGTATTACGTACCGGTTATAGTTGGCATAGCGAAGGTTCGGATAGTTGTTACAGGTGGTTGGCTTCACCCTATGGCAAGGCTTTGCGGGGTGCGTCGTTGCTAGTCCAGACATATCCGCGGTATTACGATATGAAAGATAGCGAACAAGTGCCGTCCGGGTGAAATAATAGCCAGCCGTCAGAGTGTACTAGCGATATGCCGAATCATTGGTATTTTTACCTTAGGCCCTATGAGCTTTTAAGTGAGGAGGCCCAAATGACCTTTATGCGCTGTCAAGCACCCTCAGTAAGTTTTTTCTCCCCAACATCACCCAACTCATAGGGGCTAGAGCACCCTCGATCCTCTACATTCTGATGACCCTATACTGGCATGTTCAACGCGCCTTGTGGGGCCCCCGTTCTGCAATTAAAAATAAAGGTCTTCGTAGTGGTACGAAGTATGACGAGCTGCGATTGCGAGCGCCCCGCGCCAGCAGATAAGGCGGGACTGTGATCGAGTACTGCTATCTGCCACGATTCAAACGCAAGCTAGCTCTTGTTCACATGACGATGTTCATGGAC"
count_G = 0
count_A = 0
count_C = 0
count_T = 0
for char in data:
    if char == 'G':
        count_G += 1
    elif char == 'A':
        count_A += 1
    elif char == 'C':
        count_C += 1
    elif char == 'T':
        count_T += 1
print(f"G : {count_G}")
print(f"A : {count_A}")
print(f"C : {count_C}")
print(f"T : {count_T}")