# Complementing a Strand of DNA
data = "GTAATAAATTGACTCGTTATTGAACATGATGCCCTTGCGGGGACGACCATAAGTAGGCTAGGTTCTCGAGTGCTCCGTGGCAAAACAGTCATATTGTCTCTGTCGGAAGAGCTATCGGTGGTCCACTTGACAATTATATGATCACGTCCGTTCTAAGGTCCGCTTCCCGACCCGATTAGTATCGACAAAGTATAGGACGCGGCCAGCAGGACTTCATAACCGGTCCGGAATACCATAATCGCATATCGGAGTTAGGCGGAGGGTTGACTCGCGTAAGATGACACTGCCCCTTTGGGTTACACCGCAGCTCATTCTTCCTAACCGTAAGTTATATATCCATTATTTCCTCTTTTGGGAGGTCGGTTACCTCGATGTTACGCCAGAAACGTGAGAGCGGGACTAGGCCCCATTGATCGGTACTAATATCATCAGTCCAGAGCCCTACGTGCCGGTATGTTTGGGAGTACAGGTACTACGAGTCTTACAAAGCTGCCTGGATTCTGCTGAAGAGGCTCTAGTCACAGAGGGAAACGCGTATGGCCCTCATGACGACGTCTGTCCTTGCTGCTCTGTTCTTGTCGCGTACTATTCTCTGTTTTGACGCCCGAGTACCCGCAAGGAACCGCTAGTCAAATCCCCAAATACCAGGTCTTTCGTCGTTCCAGATCCCTACACCTTTGCATCCTGCTTGCCGCGGTCTGGATTGTTGGAGCACGTGGAATCTACCACTTCTCTCGCTTAGTTTTGGTTCACTGAGATACGGGTCAGTCGATGTCATGTATCACTTTAGAAGACCCTGGTTGTGATAGGGTCCAGTCTTCGTTGATCCACATCGCCTACTTGTCATGCACCTAAAAACACAGAGAGACGGCCCCGATAGACGAGTAATCATATGGAGTAAAAAAGCTCACATTGTATCGTG"
new_data = ""
for i, e in reversed(list(enumerate(data))):
    print(i, e)
    if e == "A":
        new_data += "T"
    elif e == "T":
        new_data += "A"
    elif e == "G":
        new_data += "C"
    elif e == "C":
        new_data += "G"
print(new_data)
